name: {PACKAGE}

on:
  push:
    branch: [ master ]
  pull_request:
    branch: [ master ]

jobs:
  package-test-{PACKAGE}:
    runs-on: ubuntu-latest
    container:
      image: roscarxfel/spack-repo-testenv:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package {PACKAGE}
          spack repo add --scope=site ./
          spack install --test=root --verbose {PACKAGE}
