# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [py-msgpack-numpy,]
    container:
      image: roscarxfel/spack-centos7-python
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package ${{ matrix.package }}
          spack repo add --scope=site ./
          spack install --test=root ${{ matrix.package }}

