on:
  push:
    paths:
      - 'packages/py-msgpack-numpy/*'
  pull_request:
    paths:
      - 'packages/py-msgpack-numpy/*'

jobs:
  package-test-py-msgpack-numpy:
    runs-on: ubuntu-latest
    container:
      image: roscarxfel/spack-repo-testenv:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package py-msgpack-numpy
          echo $(spack repo list)
          spack repo add --scope=site ./
          spack install --test=root --verbose py-msgpack-numpy
