name: py-msgpack-numpy

on:
  push:
    branch: [ master ]
  pull_request:
    branch: [ master ]

jobs:
  package-test-py-msgpack-numpy:
    runs-on: ubuntu-latest
    container:
      image: roscarxfel/spack-repo-testenv:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source /opt/spack/share/spack/setup-env.sh
          echo Spack version: $(spack --version)
          echo Tests for package py-msgpack-numpy
          spack repo add --scope=site ./
          spack install --test=root --verbose py-msgpack-numpy
